# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node and different operating systems.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: install-node

on:
  push:
    branches-ignore:
      - "renovate/configure"
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 16
          - 18
        architecture:
          - x64

    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}

    # Checkout
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      # Setup PNPM
      - uses: pnpm/action-setup@v2
        name: install pnpm
        with:
          version: 7.25.0

      # Setup Node
      - uses: actions/setup-node@v3.6.0
        name: Setup Node.JS
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          cache: "pnpm"

      # Install dependencies, lint, build, and test.
      - run: pnpm install --frozen-lockfile
      - run: pnpm 'build:tsc' --if-present
      - run: pnpm test
