# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node and different operating systems.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: install-node

on:
  - push
  - pull_request

jobs:
  install:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 12
          - 14
          - 16
        architecture:
          - x64
    
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version: ${{ matrix.node }}
        check-latest: true
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
    - run: pnpm test
