name: node-pnpm

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
        node_version:
          # - 16
          - 18
        architecture:
          - x64

    name: Node ${{ matrix.node_version }} on ${{ matrix.os }} - ${{ matrix.architecture }}

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: pnpm/action-setup@v2
        name: install pnpm
        with:
          version: 7.25.0

      - uses: actions/setup-node@v3.6.0
        name: Setup Node.JS
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          cache: "pnpm"

      # Install dependencies, lint, build, and test.
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test
